-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Mylang.

module Mylang.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Mylang.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Mylang.Abs.Id where
  prt _ (Mylang.Abs.Id i) = doc $ showString i
instance Print Integer where
  prt _ (Integer i) = doc $ showString i
instance Print String where
  prt _ (String i) = doc $ showString i
instance Print Mylang.Abs.Program where
  prt i = \case
    Mylang.Abs.Prog program id_ -> prPrec i 0 (concatD [prt 0 program, prt 0 id_])

instance Print Mylang.Abs.Variable where
  prt i = \case
    Mylang.Abs.Var id_ -> prPrec i 0 (concatD [prt 0 id_])

instance Print Mylang.Abs.AssignOp where
  prt i = \case
    Mylang.Abs.AssignOp -> prPrec i 0 (concatD [doc (showString "=")])

instance Print Mylang.Abs.Type where
  prt i = \case
    Mylang.Abs.Type standardtype -> prPrec i 0 (concatD [prt 0 standardtype])
    Mylang.Abs.ArrayType n -> prPrec i 0 (concatD [doc (showString "array"), doc (showString "["), prt 0 n, doc (showString "]")])

instance Print Mylang.Abs.StandardType where
  prt i = \case
    Mylang.Abs.StdType n -> prPrec i 0 (concatD [prt 0 n])

instance Print Mylang.Abs.Statement where
  prt i = \case
    Mylang.Abs.AssignStmt variable assignop expression -> prPrec i 0 (concatD [prt 0 variable, prt 0 assignop, prt 0 expression])
    Mylang.Abs.ProcStmt procedurestatement -> prPrec i 0 (concatD [prt 0 procedurestatement])
    Mylang.Abs.CompStmt compoundstatement -> prPrec i 0 (concatD [prt 0 compoundstatement])
    Mylang.Abs.IfThenElseStmt expression statement1 statement2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 expression, doc (showString "then"), prt 0 statement1, doc (showString "else"), prt 0 statement2])
    Mylang.Abs.IfThenStmt expression statement -> prPrec i 0 (concatD [doc (showString "if"), prt 0 expression, doc (showString "then"), prt 0 statement])
    Mylang.Abs.WhileDoStmt expression statement -> prPrec i 0 (concatD [doc (showString "while"), prt 0 expression, doc (showString "do"), prt 0 statement])
    Mylang.Abs.ReadStmt readstatement -> prPrec i 0 (concatD [prt 0 readstatement])
    Mylang.Abs.WriteStmt writestatement -> prPrec i 0 (concatD [prt 0 writestatement])

instance Print Mylang.Abs.Expression where
  prt i = \case
    Mylang.Abs.EAdd expression term -> prPrec i 0 (concatD [prt 0 expression, doc (showString "+"), prt 0 term])
    Mylang.Abs.ESub expression term -> prPrec i 0 (concatD [prt 0 expression, doc (showString "-"), prt 0 term])
    Mylang.Abs.ETerm term -> prPrec i 0 (concatD [prt 0 term])

instance Print Mylang.Abs.Term where
  prt i = \case
    Mylang.Abs.EMul term factor -> prPrec i 0 (concatD [prt 0 term, doc (showString "*"), prt 0 factor])
    Mylang.Abs.EDiv term factor -> prPrec i 0 (concatD [prt 0 term, doc (showString "/"), prt 0 factor])
    Mylang.Abs.ETermF factor -> prPrec i 0 (concatD [prt 0 factor])

instance Print Mylang.Abs.Factor where
  prt i = \case
    Mylang.Abs.EInt n -> prPrec i 0 (concatD [prt 0 n])
    Mylang.Abs.EVar variable -> prPrec i 0 (concatD [prt 0 variable])
    Mylang.Abs.EParen expression -> prPrec i 0 (concatD [doc (showString "("), prt 0 expression, doc (showString ")")])

instance Print Mylang.Abs.ProcedureStatement where
  prt i = \case
    Mylang.Abs.ProcNoArgs id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "("), doc (showString ")")])
    Mylang.Abs.ProcWithArgs id_ expressionlist -> prPrec i 0 (concatD [prt 0 id_, doc (showString "("), prt 0 expressionlist, doc (showString ")")])

instance Print Mylang.Abs.ExpressionList where
  prt i = \case
    Mylang.Abs.ListExp expression -> prPrec i 0 (concatD [prt 0 expression])
    Mylang.Abs.ListExpCons expression expressionlist -> prPrec i 0 (concatD [prt 0 expression, doc (showString ","), prt 0 expressionlist])

instance Print Mylang.Abs.CompoundStatement where
  prt i = \case
    Mylang.Abs.CompSt statementlist -> prPrec i 0 (concatD [doc (showString "begin"), prt 0 statementlist, doc (showString "end")])

instance Print Mylang.Abs.StatementList where
  prt i = \case
    Mylang.Abs.ListStmt statement -> prPrec i 0 (concatD [prt 0 statement])
    Mylang.Abs.ListStmtCons statement statementlist -> prPrec i 0 (concatD [prt 0 statement, doc (showString ";"), prt 0 statementlist])

instance Print Mylang.Abs.ReadStatement where
  prt i = \case
    Mylang.Abs.ReadSt variable -> prPrec i 0 (concatD [doc (showString "read"), doc (showString "("), prt 0 variable, doc (showString ")")])

instance Print Mylang.Abs.WriteStatement where
  prt i = \case
    Mylang.Abs.WriteSt expression -> prPrec i 0 (concatD [doc (showString "write"), doc (showString "("), prt 0 expression, doc (showString ")")])
