## File generated by the BNF Converter (bnfc 2.9.5).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : Mylang/Test

# Rules for building the parser.

Mylang/Abs.hs Mylang/Lex.x Mylang/Par.y Mylang/Print.hs Mylang/Test.hs : grammar/mylang.cf
	bnfc --haskell -d grammar/mylang.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Mylang/Test : Mylang/Abs.hs Mylang/Lex.hs Mylang/Par.hs Mylang/Print.hs Mylang/Test.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f Mylang/*.hi Mylang/*.o Mylang/*.log Mylang/*.aux Mylang/*.dvi

distclean : clean
	-rm -f Mylang/Abs.hs Mylang/Abs.hs.bak Mylang/ComposOp.hs Mylang/ComposOp.hs.bak Mylang/Doc.txt Mylang/Doc.txt.bak Mylang/ErrM.hs Mylang/ErrM.hs.bak Mylang/Layout.hs Mylang/Layout.hs.bak Mylang/Lex.x Mylang/Lex.x.bak Mylang/Par.y Mylang/Par.y.bak Mylang/Print.hs Mylang/Print.hs.bak Mylang/Skel.hs Mylang/Skel.hs.bak Mylang/Test.hs Mylang/Test.hs.bak Mylang/XML.hs Mylang/XML.hs.bak Mylang/AST.agda Mylang/AST.agda.bak Mylang/Parser.agda Mylang/Parser.agda.bak Mylang/IOLib.agda Mylang/IOLib.agda.bak Mylang/Main.agda Mylang/Main.agda.bak Mylang/mylang.dtd Mylang/mylang.dtd.bak Mylang/Test Mylang/Lex.hs Mylang/Par.hs Mylang/Par.info Mylang/ParData.hs Makefile
	-rmdir -p Mylang/

# EOF
